version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependabot-bump"
      - "pip-bump"
    reviewers:
      - "seven7ty"
    commit-message:
      prefix: "pip"
      prefix-development: "pip dev"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "seven7ty"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependabot-bump"
      - "gh-actions-bump"
    reviewers:
      - "seven7ty"
    commit-message:
      prefix: "github actions"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "seven7ty"
