version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-bump"
      - "pip-bump"
    reviewers:
      - "itsmewulf"
    commit-message:
      prefix: "pip"
      prefix-development: "pip dev"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "itsmewulf"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-bump"
      - "gh-actions-bump"
    reviewers:
      - "itsmewulf"
    commit-message:
      prefix: "github actions"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "itsmewulf"
