website:
- changed-files:
  - any-glob-to-any-file: ['docs/**/*']
cogs:
- changed-files:
  - any-glob-to-any-file: ['cogs/**/*']
root:
- changed-files:
  - any-glob-to-any-file: ['./*']
locale:
- changed-files:
  - any-glob-to-any-file: ['resources/locale/**/*']
